import MainLayout from '@/layouts/Main';
import { useSession } from 'next-auth/react';
import Link from 'next/link';

interface Props {
 domain: string
}

export default function PrivacyPolicy({ domain }: Props) {
	const { data: session, status } = useSession();
	if (status == 'loading') return null;

	return (
		<MainLayout user={session?.user}>
			<div className="container">
				<h1>Privacy Policy</h1>
				<p>Your privacy is important to us. It is Team Egglord policy to respect your privacy regarding any information we may collect from you across our website, <Link href={domain}>{domain}</Link>, and other sites we own and operate.</p>
  			<p>We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.</p>
  			<p>We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.</p>
  			<p>We don’t share any personally identifying information publicly or with third-parties, except when required to by law.</p>
  			<p>Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.</p>
  			<p>You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.</p>
  			<p>Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.</p>
  			<div id="definitions">
					<h3><a href="definitions" style={{ textDecoration: 'none', color: 'black' }}>Definitions</a></h3>
					<p>For the purposes of this Privacy Policy:</p>
					<ul>
						<li><b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
						<li><b>Company</b> (referred to as either the Company, We, Us or Our in this Agreement) refers to API Egglord.</li>
						<li><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</li>
						<li><b>Website</b> refers to API Egglord, accessible from <Link href={domain}>{domain}</Link></li>
						<li><b>Service</b> refers to the Website.</li>
						<li><b>Country</b> refers to: England</li>
						<li><b>Third-party Social Media Service</b> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
						<li><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</li>
						<li><b>Cookies</b> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
						<li><b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
						<li><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
					</ul>
  			</div>
				<div id="cookies">
					<h3>The use of the Cookies</h3>
					<h5>Type of Cookies We Use</h5>
					<p>Cookies can be Persistent or Session Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.</p>
					<p>We use both session and persistent Cookies for the purposes set out below:</p>
					<ul>
						<li>Necessary / Essential Cookies</li>
						<ul>
							<li>Type: Session Cookies</li>
							<li>Administered by: Us</li>
							<li>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
						</ul>
						<li>Functionality Cookies</li>
						<ul>
							<li>Type: Persistent Cookies</li>
							<li>Administered by: Us</li>
							<li>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
						</ul>
					</ul>
					<h5>Your Choices Regarding Cookies</h5>
					<p>If You prefer to avoid the use of Cookies on the Website, first You must disable the use of Cookies in your browser and then delete the Cookies saved in your browser associated with this website. You may use this option for preventing the use of Cookies at any time.</p>
					<p>If You do not accept Our Cookies, You may experience some inconvenience in your use of the Website and some features may not function properly.</p>
					<p>If You&apos;d like to delete Cookies or instruct your web browser to delete or refuse Cookies, please visit the help pages of your web browser.</p>
					<ul>
						<li>For the Chrome web browser, please visit this page from Google: Google support</li>
						<li>For the Internet Explorer web browser, please visit this page from Microsoft: <a href="http://support.microsoft.com/kb/278835">http://support.microsoft.com/kb/278835</a></li>
						<li>For the Firefox web browser, please visit this page from Mozilla: <a href="https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored">https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored</a></li>
						<li>For the Safari web browser, please visit this page from Apple: Apple support</li>
						<li>For any other web browser, please visit your web browserEgglordofficial web pages.</li>
					</ul>
				</div>
				<p>This policy is effective as of 29 May 2023.</p>
			</div>
		</MainLayout>
	);
}

export async function getServerSideProps() {
	return { props: { domain: process.env.NEXTAUTH_URL } };
}
